### ISSUE TITLE
Getting "undefined method `autoload_paths' for #<Rails::Configuration..." when running a rake command

### ISSUE THREAD

**Issue by ghost** [jamis/bucketwise#26]
This seems to have been introduced with commit 6d8924d911077b78a712
